namespace AppLogic.Enums
{
    public enum ItemType
    {
        Unknown,
        Key,
        SmallKey,
        Corkscrew,
        Bottle,
        OpenedBottle,
        Extinguisher,
        Shovel,
        Note,
        Pickaxe,
        PurpleKey,
        WineBottle,
        OpenedWineBottle,
        Crowbar,
        KeyFragment,
        SecondKeyFragment,
        DirtLump,
        GreenKey,
        CarvingKnife,
        Wood,
        Paint,
        Figurine,
        PaintedFigurine,
        Diary,
        Handle,
        FireExtinguisherTank,
        Basket,
        Flowers,
        BasketWithFigurine,
        BasketsWithGifts
    }
}
