namespace Adventure.Enums
{
    public enum Items
    {
        Unknown,
        Key,
        SmallKey,
        Corkscrew,
        Bottle,
        OpenedBottle,
        Extinguisher,
        Shovel,
        Note,
        Pickaxe,
        PurpleKey,
        WineBottle,
        OpenedWineBottle,
        Crowbar,
        KeyFragment,
        SecondKeyFragment,
        DirtLump,
        GreenKey,
        CarvingKnife,
        Wood,
        Paint,
        Figurine,
        PaintedFigurine,
        Diary
    }
}
